---
- hosts: all
  remote_user: ubuntu
  become_method: sudo
  become: true
  vars:
    project_name: "Authors Haven App Database"
    database_name: "balder-ah"
    databas_user: "postgres"
    db_password: "postgres"

  tasks:
    - name: Reset contents of apt list
      shell: |
        sudo rm -rf /var/lib/apt/lists/*
        sudo apt-get update

    - name: Install latest version of bash, OpenSSl, and libssl
      apt: name={{ item }} update_cache=true state=latest
      with_items:
        - bash
        - openssl
        - libssl-dev
        - libssl-doc
      tags: packages

    - name: Install PostgreSQL
      apt: name={{ item }} update_cache=true state=installed
      with_items:
        - postgresql
        - postgresql-contrib
        - libpq-dev
        - python-psycopg2
      tags: packages

    - name: Start PostgreSQL
      service: name=postgresql state=started enabled=yes

    - name: Create database
      sudo_user: postgres
      postgresql_db:
        name={{ database_name }}
        encoding='UTF-8'
        lc_collate='en_US.UTF-8'
        lc_ctype='en_US.UTF-8'
        template='template0'
        state=present

    - name: Provide user credentials to connect to database
      sudo_user: postgres
      postgresql_user:
        db={{ database_name }}
        name={{ databas_user }}
        password={{ db_password }}
        priv=ALL
        state=present
